"""PR creation node for Task Takeover workflow."""

import asyncio
import contextlib
import logging
from pathlib import Path
from typing import cast

from forge.integrations.github.client import GitHubClient
from forge.integrations.jira.client import JiraClient
from forge.orchestrator.checkpointer import set_pr_ticket_index
from forge.workflow.nodes.pr_creation import (
    open_pull_request_from_fork,
    prepare_pull_request_target,
)
from forge.workflow.nodes.workspace_setup import teardown_workspace
from forge.workflow.task_takeover.state import TaskTakeoverState as WorkflowState
from forge.workflow.utils import update_state_timestamp
from forge.workspace.git_ops import GitOperations
from forge.workspace.manager import Workspace

logger = logging.getLogger(__name__)


async def cleanup_podman_containers(ticket_key: str) -> None:
    """Stop and remove any running or stopped podman containers related to the ticket.

    Args:
        ticket_key: Jira ticket key to match container names.
    """
    try:
        # Find containers with name matching forge-{ticket_key}-*
        proc = await asyncio.create_subprocess_exec(
            "podman",
            "ps",
            "-a",
            "--filter",
            f"name=forge-{ticket_key}-",
            "--format",
            "{{.Names}}",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        container_names = [name.strip() for name in stdout.decode().splitlines() if name.strip()]

        for name in container_names:
            logger.info(f"Stopping container: {name}")
            stop_proc = await asyncio.create_subprocess_exec(
                "podman",
                "stop",
                "-t",
                "5",
                name,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
            )
            await stop_proc.wait()

            logger.info(f"Removing container: {name}")
            rm_proc = await asyncio.create_subprocess_exec(
                "podman",
                "rm",
                "-f",
                name,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
            )
            await rm_proc.wait()
    except Exception as e:
        logger.warning(f"Error during podman container teardown for {ticket_key}: {e}")


async def create_task_takeover_pr(state: WorkflowState) -> WorkflowState:
    """Create a pull request from workspace changes for the task takeover workflow.

    This node:
    1. Synchronizes local changes with repository fork.
    2. Pushes local changes using GitOperations.
    3. Opens a Pull Request using GitHubClient.
    4. Posts the PR markdown link as a comment on Jira.
    5. Transitions Jira ticket status to "In Review".
    6. Teardown the workspace and container runner, freeing all resources.

    Args:
        state: Current task takeover workflow state.

    Returns:
        Updated state with PR details, workspace cleared.
    """
    ticket_key = state["ticket_key"]
    workspace_path = state.get("workspace_path")
    current_repo = state.get("current_repo", "")
    branch_name = state.get("context", {}).get("branch_name") or f"forge/{ticket_key.lower()}"

    if not workspace_path:
        logger.error(f"No workspace for PR creation on {ticket_key}")
        return cast(
            WorkflowState,
            update_state_timestamp(
                {
                    **state,
                    "last_error": "Workspace not set up",
                    "current_node": "create_task_takeover_pr",
                }
            ),
        )

    github = GitHubClient()
    jira = JiraClient()

    try:
        # Step 1: Set up GitOperations
        workspace = Workspace(
            path=Path(workspace_path),
            repo_name=current_repo,
            branch_name=branch_name,
            ticket_key=ticket_key,
        )
        git = GitOperations(workspace)

        # Step 2: Fetch Jira issue details to construct the PR title/description
        ticket_summary = ""
        ticket_description = ""
        try:
            ticket_issue = await jira.get_issue(ticket_key)
            ticket_summary = ticket_issue.summary or ""
            ticket_description = ticket_issue.description or ""
        except Exception as e:
            logger.warning(f"Could not fetch ticket details for PR: {e}")

        pr_title = f"[{ticket_key}] {ticket_summary or 'Implementation'}"
        pr_body = (
            f"This PR implements ticket **{ticket_key}**.\n\n"
            f"### Ticket Description\n"
            f"{ticket_description or '(No description provided)'}\n\n"
            f"---\n"
            f"*Generated by [Forge](https://github.com/forge-sdlc/forge) SDLC Orchestrator*"
        )

        # Step 3: Prepare the fork, push local changes, and open the pull request
        pr_target = await prepare_pull_request_target(github, git, current_repo)
        git.push_to_fork()
        pr_data = await open_pull_request_from_fork(
            github,
            pr_target,
            branch_name=branch_name,
            title=pr_title,
            body=pr_body,
        )
        pr_url = pr_data.get("html_url", "")
        pr_number = pr_data.get("number")

        # Step 4: Post the PR link as a comment on Jira
        pr_label = f"PR #{pr_number}" if pr_number is not None else "Pull Request"
        comment_text = f"Pull request created: {pr_url}"
        await jira.add_comment(ticket_key, comment_text)

        # Create remote link in Jira as well for better integration
        with contextlib.suppress(Exception):
            await jira.create_remote_link(ticket_key, pr_url, pr_label)

        try:
            await set_pr_ticket_index(pr_url, ticket_key)
        except Exception:
            logger.warning(
                f"Failed to index PR {pr_url} to {ticket_key}; "
                "GitHub event routing will fall back to name-based extraction",
                exc_info=True,
            )

        # Step 5: Transition the Jira ticket status to "In Review"
        await jira.transition_issue(ticket_key, "In Review")

        # Update PR URL lists
        pr_urls = state.get("pr_urls", [])
        if pr_url and pr_url not in pr_urls:
            pr_urls.append(pr_url)

        # Update state with PR information before teardown
        state_with_pr = {
            **state,
            "pr_urls": pr_urls,
            "current_pr_url": pr_url,
            "current_pr_number": pr_number,
            "fork_owner": pr_target.fork_owner,
            "fork_repo": pr_target.fork_repo,
        }

        # Step 6: Teardown workspace and container runner resources
        # Clean up any lingering container runners
        await cleanup_podman_containers(ticket_key)

        # Clean up files and delete workspace
        teardown_state = await teardown_workspace(cast(WorkflowState, state_with_pr))

        return cast(
            WorkflowState,
            update_state_timestamp(
                {
                    **teardown_state,
                    "current_node": "wait_for_ci_gate",
                    "is_paused": False,
                    "last_error": None,
                }
            ),
        )

    except Exception as e:
        logger.error(f"Task takeover PR creation node failed for {ticket_key}: {e}")
        return cast(
            WorkflowState,
            update_state_timestamp(
                {
                    **state,
                    "last_error": str(e),
                    "current_node": "create_task_takeover_pr",
                    "retry_count": state.get("retry_count", 0) + 1,
                }
            ),
        )
    finally:
        await github.close()
        await jira.close()
